[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arghandle"
version = "2.6.2"
description = "A simple, clean alternative to argparse"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "alanbutidk" }
]
keywords = ["cli", "args", "arguments", "argparse"]
license = "GPL-3.0-only"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
[project.scripts]

arghandle = "arghandle.arghandle:Cli"

[tool.setuptools]
include-package-data = true

[tool.setuptools.exclude-package-data]
"*" = [".gitignore", ".git", ".abuild", ".ruff_cache", "DOCS.md"]

